global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'local-dev'
    environment: 'development'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Load rules
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI Gateway
  - job_name: 'fastapi-gateway'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'

  # BentoML Model Server
  - job_name: 'bentoml-server'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'

  # Milvus
  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus:9091']

  # PostgreSQL Exporter (if installed)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis Exporter (if installed)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Node Exporter (for host metrics, if installed)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
